[workspace]
resolver = "2"

members = [
	"bin/millau/node/*",
	"bin/runtime-common",
	"bin/substrate2/runtime",
	"bin/substrate2/node/*",
	"primitives_bridge/*",
	"fuzz/*",
	"modules/*",
	#"relays/*",
]
