[package]
name = "node-executor"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
scale-info = { version = "2.1.1", features = ["derive"] }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
node-primitives = { version = "2.0.0", path = "../primitives" }
kitchensink-runtime = { version = "3.0.0-dev", path = "../runtime" }
sc-executor = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false}
sp-core = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false}
sp-keystore = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false}
sp-state-machine = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
sp-trie = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false}

[dev-dependencies]
criterion = "0.3.0"
futures = "0.3.21"
wat = "1.0"
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false}
frame-system = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
node-testing = { version = "3.0.0-dev", path = "../testing" }
pallet-balances = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
pallet-contracts = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false}
pallet-im-online = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
pallet-sudo = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
pallet-timestamp = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false}
pallet-treasury = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
pallet-transaction-payment = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
sp-application-crypto = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
pallet-root-testing = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
sp-consensus-babe = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
sp-externalities = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
sp-keyring = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }
sp-runtime = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.36", default-features = false }

[features]
stress-test = []

[[bench]]
name = "bench"
harness = false
